policies:
  - name: account-check-config-services
    resource: account
    mode:
      type: periodic
      role: VentureAdminRole
      schedule: "rate(4 hours)"
    filters:
      - type: check-config
        all-resources: true
        global-resources: true
        running: true
